### ISSUE TITLE
Veřejné uživatelské profily 1.0

### ISSUE THREAD

**Issue by zoul** [cesko-digital/app#1042]
## Stručně

Chceme do aplikace přidat veřené uživatelské profily. Každý uživatel bude mít stránku, na které budou vidět například jeho dovednosti a kontaktní informace. Kromě toho vznikne i adresář všech uživatelů, kde bude možné profily prohledávat podle různých kritérií. Hlavním účelem těchto funkcí je zjednodušit vyhledávání lidí (například ze strany č.d na projekty nebo ze strany neziskovek na konzultace a pomoc) a propojování lidí navzájem (například i podle regionu).

## Detaily

Neuspořádané poznámky k návrhu i implementaci, WIP.

* Veřejný profil musí být opt-in, nemůžeme zveřejňovat profilové informace bez jasného souhlasu.
    * Chceme čistě binární opt-in (chci/nechci), anebo víc možností, například soukromý / po přihlášení / veřejný?
    * Nedávalo by smysl v tomto ohledu i nastavení, co všechno chci dělat? Například: Nabízím krátké konzultace / Kratší placenou práci / Delší placenou práci / Mentoring / …?
* URL stránek můžou být třeba `/people` pro adresář a `/people/{id}` pro konkrétního člověka.
* V profilech konečně rozumně využijeme data z „mapy dobrovolníků“. Můžeme ukázat, kde se kdo pohybuje, a podle toho se lidi můžou propojovat, například pokud hledám někoho na Python z Brna.
* Velmi se nabízí využít existujících vazeb v tabulce týmových zapojení (Teams) a zobrazit na profilu i zapojení uživatele na projektech.
* Chceme měřit konverze kontaktního tlačítka

## TODO

* [x] https://github.com/cesko-digital/app/issues/1045
* [x] https://github.com/cesko-digital/app/issues/1046
* [x] https://github.com/cesko-digital/app/issues/1049
* [x] https://github.com/cesko-digital/app/issues/1050
* [x] https://github.com/cesko-digital/app/issues/1064

## Na příště

Přidali jsme další položky do registrace, tak by bylo dobré vrátit pozornost k https://github.com/cesko-digital/app/issues/1017 a část těch věcí, zejména ty nepovinné, z registrace přesunout do nějakého onboardingu? Ať ta registrace zůstane maximálně jednoduchá.

* #1054
* #1055
* #1056
* #1052
* #1051
* #1053
* #1058
